services:
  - type: web
    name: taskify-ai
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: JAVA_OPTS
        value: -Xmx256m -Xss512k -Dfile.encoding=UTF-8
    autoDeploy: true