services:
  - type: web
    name: taskify-ai
    env: java
    plan: free
    buildCommand: mvn clean package
    startCommand: java -jar target/dependency/webapp-runner.jar target/taskifyai.war --port $PORT
    envVars:
      - key: JAVA_VERSION
        value: 11
    autoDeploy: true